### ISSUE TITLE
教程里的一点小问题

### ISSUE THREAD

**Issue by RanHoNg** [ugukkylbklaom/Vultr-SS-Firewall#1]
**首先，十分感谢能提供这么详细的教程。在按教程操作时，目前为止遇到了一点小问题（还没试FS）**
* 步骤10、VPS端安装Shadowsocks：命令pip install gevent、pip install M2Crypto、pip install shadowsocks出错。
 * 可能原因：没有安装gcc
 * 解决：yum install gcc
* 步骤10的json文件中：【"server_port”:XXX,#自定义】第二个双引号是中文输入法
* 是不是应该在步骤10 最后加上命令： service iptables save

*谢谢教程*

**Comment by ugukkylbklaom** [comment]
感谢纠错，已修改

**Comment by ugukkylbklaom** [comment]
欢迎使用我的推广链接，搭配优惠码

点击http://www.vultr.com/?ref=6892882或者http://www.vultr.com/?ref=6917132-3B 进入官网，点sign up 注册(通过第二个链接注册可得20$现金抵用，配合20$优惠码，总共40$)，优惠码：NGINX20 (20美元优惠码，时效1年，使用时，先remove预设的50$新账户优惠码，50$的不划算，只能用2个月，而20$可以用4个月)，支付方式选择Palpay(需要预存5$－250$，直接预存Paypal的10$新手奖励）。

这样一共就有免费的30$/50$(通过第二个链接注册)，可以用6 or 10个月

**Comment by kang000feng** [comment]
20$现金抵用与20$优惠码不能重复,只能二选一, 且无论哪一种时效只有一个月.

**Comment by ugukkylbklaom** [comment]
@kang000feng  20$优惠码只有1个月了吗？ 我用的时候还是一年的
那50$的使用期限是多久？ 你Payapl的新手奖励有使用吗？

**Comment by ugukkylbklaom** [comment]
@kang000feng  客服原话是
```
The NGINX20 expires one year after it's applied. We do not combine promotions. 
```
20$的优惠码有效期1年，Vultr优惠不可以叠加

**Comment by kang000feng** [comment]
@ugukkylbklaom Payapl的新手奖励不是早结束了吗？

**Comment by ugukkylbklaom** [comment]
@kang000feng  名义上早结束了，但是如果你是第一次注册Paypal账户，绑定信用卡之后，直接联系客服，要求一个10$的新手奖励，一般客服都会给你的，只要你态度好的话
