### ISSUE TITLE
请问ubuntu 桌面操作系统怎么用finalspeed的客户端

### ISSUE THREAD

**Issue by bigpigeon** [ugukkylbklaom/Vultr-SS-Firewall#5]
直接用java启动貌似不行，会报错

**Comment by ugukkylbklaom** [comment]
@bigpigeon  你好，我没用过ubuntu诶，你可以参考自己的报错代码和这个 http://blog.lihanming.me/2016-05-03-%E5%9C%A8-Ubuntu-16-04-%E4%B8%8A%E9%83%A8%E7%BD%B2-FinalSpeed-%E5%8A%A0%E9%80%9F.html

**Comment by bigpigeon** [comment]
这个也只是ubuntu的服务端配置吧，不过我现在想尝试用kcptun
这个基本支持任何平台
