### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by Too-Naive** [ugukkylbklaom/Vultr-SS-Firewall#6]
完全没必要把伺服器提供商直接列舉出來 需要什麼自己去找不是更好嗎 有hosts做跳板 自己找伺服器提供商 現在網路那麼發達 找到一家好的伺服器提供商並不是什麼難事

一個伺服器的網段也就那幾個 隨便整個網段封鎖其他用戶完全就不用用伺服器了 linode已經被監視了所以還是覺得不夠嗎？

利益相關:伺服器使用者

**Comment by ugukkylbklaom** [comment]
IRRELEVANT
