### ISSUE TITLE
More Shadowsocks download links in Wiki?

### ISSUE THREAD

**Issue by Crystal-RainSlide** [ugukkylbklaom/Vultr-SS-Firewall#8]
shadowsocks.org is behind the wall.

**Comment by ugukkylbklaom** [comment]
Thank you for contacting me.  I'm not sure what information you are looking for, if you want to download shadowsocks, you could download it through [OS X](https://github.com/ugukkylbklaom/Vultr-SS-Firewall/wiki/OS-X-%E7%B3%BB%E7%BB%9F%E6%95%99%E7%A8%8B) or [WIN](https://github.com/ugukkylbklaom/Vultr-SS-Firewall/wiki/WIN%E7%B3%BB%E7%BB%9F%E6%95%99%E7%A8%8B) according to your system
