### ISSUE TITLE
还有别的优化速度和稳定的方法吗

### ISSUE THREAD

**Issue by dursss** [ugukkylbklaom/Vultr-SS-Firewall#9]
你好，我按照你的教程搭建的，速度已经很不错了，比我之前买的要好多了，请问还有其他优化的方法吗，想加进去看看

**Comment by ugukkylbklaom** [comment]
@dursss 您好，目前主流的就4种，你可以试试
finalspeed(作者推收费软件，fs的源代码已删除，但有很多fork)
bbr
kcp(包括kcptun)
锐速(只有这个不是开源，网上有破解版)

劳烦向有需要的人推荐我的教程  谢谢
https://github.com/ugukkylbklaom/Vultr-SS-Firewall/wiki

**Comment by dursss** [comment]
嗯，教程里能不能加一下怎么开启多用户？
